数组（Array）是python中重要的数据结构，python中的numpy包提供了对数组的支持

# 数组的创建

## 使用np.array从列表创建

用于将列表转化为数组

**np.array(object, dtype)**：
- object：用于指定输入数据
- dtype：用于指定数组中元素的数据类型。如果未指定，则根据输入自动推断。

In [18]:
import numpy as np

# 创建一维数组
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [19]:
# 创建二维数组
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## 从内置函数创建

### 使用np.zeros()创建全零数组

用于创建一个所有元素都为零的数组

**np.zeros(shape, dtype)**：
- shape：用于指定数组的形状。可以是一个整数（表示一维数组的长度）或一个元组（表示多维数组的维度）
- dtype：用于指定数组中元素的数据类型。默认值为float（浮点数）

In [20]:
np.zeros((3, 4))  # 创建 3x4 的全零数组

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 使用np.ones()创建全一数组

用于创建一个所有元素都为1的数组

**np.ones(shape, dtype)**：
- shape：用于指定数组的形状。可以是一个整数（表示一维数组的长度）或一个元组（表示多维数组的维度）
- dtype：用于指定数组中元素的数据类型。默认值为float（浮点数）

In [21]:
np.ones((2, 3))  # 创建 2x3 的全一数组

array([[1., 1., 1.],
       [1., 1., 1.]])

### 使用np.full()创建指定数值的数组

用于创建一个所有元素都为指定值的数组

**np.full(shape, fill_value, dtype)**：
- shape：用于指定数组的形状。可以是一个整数（表示一维数组的长度）或一个元组（表示多维数组的维度）
- fill_value：用于指定数组中每个元素的值
- dtype：用于指定数组中元素的数据类型。默认值为float（浮点数）

In [22]:
np.full((2, 2), 7)  # 创建 2x2 的全 7 数组

array([[7, 7],
       [7, 7]])

### 使用np.arange()创建连续数值的数组

用于创建一个等差数列的数组

**np.arange(start, stop, step, dtype)**：
- start：数列的起始值（包含 start）。默认值为0
- stop：数列的终止值（不包含 stop）
- step：数列的步长，即每次增加或减少的值。默认值为1
- dtype：用于指定数组中元素的数据类型。默认值为float（浮点数）

In [24]:
np.arange(0, 10, 2)  # 从 0 到 10（不含），步长为 2

array([0, 2, 4, 6, 8])

### 使用np.linspace()创建等间距数值的数组

用于生成在指定区间内均匀分布的一组数值

**np.linspace(start, stop, step, dtype)**：
- start：数列的起始值（包含 start）。默认值为0
- stop：数列的终止值
- num：要生成的数值个数
- dtype：用于指定数组中元素的数据类型。默认值为float（浮点数）

In [26]:
np.linspace(0, 1, 5)  # 在 0 和 1 之间生成 5 个等间距的数值

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 创建随机数组

#### np.random.randint(low, high, size)生成指定范围内的随机整数数组

- **low**：生成范围最小值
- **high**：生成范围最大值
- **size**：生成个数

In [29]:
# 生成50个介于0-100的随机整数
np.random.randint(0, 100, size=50)

array([21, 58, 67, 47, 56, 47, 18, 43, 35, 54, 63, 41, 47, 21, 63, 47, 31,
       67, 61, 16, 90, 83, 88,  4,  2, 78, 29, 40,  6,  1, 59, 97, 38, 29,
       46,  3, 68, 36, 75, 62, 79, 36, 60, 16, 23, 75,  6, 62, 77, 28])

#### np.random.uniform(low, high, size)生成指定范围内的随机浮点数数组

- **low**：生成范围最小值
- **high**：生成范围最大值
- **size**：生成个数

In [32]:
# 生成50个介于0-100的随机浮点数
np.random.uniform(0, 100, size=50)

array([93.8676774 , 82.64014504, 82.56156341, 34.6580455 , 28.76258652,
       59.06835201, 18.33713333, 48.70096899, 12.17487015, 54.50726946,
       93.82252141,  1.88525202,  9.00749133, 28.5603837 , 74.18995209,
       88.4457878 , 39.07340661, 60.95529861, 17.7285344 , 97.74216998,
       73.20556059, 15.67899116,  5.7622826 , 24.24763393, 64.42253916,
       51.18181173, 83.42907241, 84.67805255, 98.97703127, 46.66207389,
       68.30641242, 69.7324464 , 23.6986347 , 56.96139847, 20.30083483,
       83.64137738, 13.06014247, 22.62746304, 37.1417778 , 97.64875645,
       69.1150285 , 48.9540445 , 37.64756707, 42.79780369, 39.63966754,
       66.20462961, 45.55082384, 75.54894807, 91.98068651, 19.97425995])

#### np.random.rand(size)生成0到1之间的随机浮点数组

- **size**：生成个数

In [35]:
# 生成50个0-1之间的随机浮点数
np.random.rand(50)

array([7.31987154e-01, 8.45841750e-01, 2.94307877e-01, 8.98397730e-01,
       6.59665839e-01, 3.59292119e-01, 3.42818753e-01, 5.29979534e-01,
       3.69529106e-02, 8.01707385e-01, 3.00284753e-01, 7.01076806e-01,
       8.52299020e-02, 4.86982359e-01, 6.77753566e-01, 7.51706753e-01,
       5.59353715e-01, 8.37693364e-01, 5.70305859e-02, 4.37550952e-02,
       7.92815605e-01, 1.80588159e-02, 6.31120172e-04, 4.78946022e-01,
       9.33539195e-01, 7.96496237e-01, 1.97545129e-02, 9.79275010e-01,
       2.74170545e-01, 1.95669448e-01, 2.97480157e-01, 1.31312606e-01,
       5.90200368e-01, 1.52417326e-01, 8.73955115e-01, 6.98403697e-01,
       4.74555799e-01, 6.04185433e-01, 2.64970864e-01, 6.94649476e-02,
       9.64565554e-02, 3.27605609e-01, 6.58308453e-01, 6.74844620e-01,
       3.55650568e-01, 2.48989624e-01, 1.88762173e-02, 3.73242446e-01,
       4.96024894e-01, 3.72023755e-01])

#### np.random.randn(size)生成符合标准正态分布（均值为0，标准差为1）的随机数数组

- **size**：生成个数

In [38]:
# 生成50个符合标准正态分布的随机数
np.random.randn(50)

array([-0.32484852,  0.24848763,  0.55696485,  0.25103901,  0.12927514,
       -0.0656895 ,  0.14483852,  0.66216052,  0.87665302, -0.25604896,
        0.77203587, -0.700708  ,  0.24649002, -2.61781911,  0.18449938,
       -0.08399425,  1.28914536, -1.32504683,  1.44991552,  0.29431464,
        1.25488307,  1.34406198,  0.87057139, -1.88213875, -0.34591333,
       -0.07849226, -0.31275365,  0.49705391,  1.04617946, -0.48027904,
        1.06964981,  2.04605406,  0.16050242, -0.07015616, -1.66475399,
        0.82790826, -0.98130468, -0.13419153, -1.48280092, -1.09379386,
       -0.85949316, -0.54412735,  1.61031938, -0.72851832, -0.45699401,
        2.06754069, -1.13717149, -0.69270457, -0.38092805, -0.15442209])

#### np.random.permutation(arr)对数组进行随机排列

In [41]:
arr = np.array([1, 2, 3, 4, 5])
np.random.permutation(arr)

array([3, 5, 4, 1, 2])


# 数组的属性

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

## .shape查看数组形状

In [43]:
# 返回数组的形状
arr.shape

(2, 3)

## .size查看数组中元素总个数

In [44]:
# 数组中包含的元素总数量
arr.size

6

## .dtype查看数组中元素的数据类型

In [45]:
# 数组中数据类型
arr.dtype

dtype('int64')

# 数组的主要方法

## 数组索引与访问

### 一维数组索引

In [49]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [50]:
arr[-1]

50

### 二维数组索引

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
print(arr[0, 1])  # 输出：2
print(arr[1, :])  # 输出：[4 5 6]，取第二行所有元素
print(arr[:, 0])  # 输出：[1 4]，取第一列所有元素

2
[4 5 6]
[1 4]


### 条件选择

In [55]:
# 使用布尔表达式进行条件选择
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr[arr>3]

array([4, 5, 6])

## 数组运算

### 元素级运算

In [58]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [59]:
print(arr + 10)  # 输出：[20 30 40 50 60]
print(arr * 2)   # 输出：[ 20  40  60  80 100]

[20 30 40 50 60]
[ 20  40  60  80 100]


### 数组间运算

In [60]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # 输出：[5 7 9]

[5 7 9]


### 广播机制

当数组的形状不同但兼容时，NumPy 会自动扩展较小的数组以匹配形状进行计算

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr +10 )  # 每个元素加 10

[[11 12 13]
 [14 15 16]]


## 数组中统计值计算

In [64]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())       # 总和：15
print(arr.mean())      # 平均值：3.0
print(arr.max())       # 最大值：5
print(arr.min())       # 最小值：1
print(arr.std())       # 标准差：1.414
print(arr.var())       # 方差：2.0

15
3.0
5
1
1.4142135623730951
2.0


## 数组形状修改

### 修改形状

In [65]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # 改为 2x3 的数组
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

### 数组展平

In [66]:
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
reshaped.ravel()  # 展平为一维数组

array([1, 2, 3, 4, 5, 6])

## 数组的合并与分割

### 数组合并

In [68]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(np.concatenate([arr1, arr2]))  # 输出：[1 2 3 4]

[1 2 3 4]


### 数组分割

In [69]:
arr = np.array([1, 2, 3, 4, 5, 6])
split = np.split(arr, 3)  # 平均分成 3 组
print(split)

[array([1, 2]), array([3, 4]), array([5, 6])]
